### ISSUE TITLE
Ferolli/hyundai heatpump

### ISSUE THREAD

**Issue by themayna** [wuwentao/midea_ac_lan#281]
### Device type and model (or SN)

Ferroli omnia m 3.2 hi 3.8

### The description of new feature

unfortunatelly this does not work anymore with my ferolli omnia 3.2 heatpump, i only get this message "No new available appliances found on the network" :(

**Comment by erikgieseler** [comment]
Alternatively, have you tried adding the heat pump manually with the IP address?

**Comment by rokam** [comment]
Try version 0.5.7, a critical bug was fixed.

**Comment by themayna** [comment]
yea, i updated to 0.5.7 and tried via manual ip, but my heatpump is still not found :(
<img width="580" alt="Screenshot 2024-08-15 at 6 16 57 PM" src="https://github.com/user-attachments/assets/198385a1-0fcd-4f19-b0f7-e5c123dde287">

**Comment by erikgieseler** [comment]
> yea, i updated to 0.5.7 and tried via manual ip, but my heatpump is still not found :( <img alt="Screenshot 2024-08-15 at 6 16 57 PM" width="580" src="https://private-user-images.githubusercontent.com/11145984/358277069-198385a1-0fcd-4f19-b0f7-e5c123dde287.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzU3MjEsIm5iZiI6MTcyMzczNTQyMSwicGF0aCI6Ii8xMTE0NTk4NC8zNTgyNzcwNjktMTk4Mzg1YTEtMGZjZC00ZjE5LWIwZjctZTVjMTIzZGRlMjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE1MjM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MGFlNmQzMDY5MTljODVlMTZjNzM3NjY2ZDAyZGM0YjhmNGU2MzAzNGYyN2I5NDU4YTQ3ZmM5MDJjYjZiYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7WEV4H5pO0UPFo4UMxz6hWEcb0DotjJZNkKjdpgZevY">

Use the real IP of the heat pump (check your router), not “auto”.

**Comment by rokam** [comment]
Also, please provide your logs. 
https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#debug

**Comment by themayna** [comment]
no waaayyyy, so i restarted my deco network and reintegrated the pump controller(i think this is the winning point), tried to add it via manual ip and almost works, still have a few "unknown" sensors but this gets solved in time(same issue as the older repo).
ps: auto still does nothing :D 

many thanks
